apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtekNDQm9nQXdJQkFnSFFBakFOTkJna3Foa2lHOXcwQkFRc0ZBREFOTVJRd0dnWURWUVFERXd3cmRXSmwKY201bGRHVnlaekFlRncweU56QTRNekV3T0RReU1UaGFGdzB6TkRBNE16RXdPRFF5TVRoYU1BMHhHekFYQmdOVgpCQV1NRUNselpXUnpZWEp6Y21Wa1p6R0NfX19fX19fX0VORE9GR19fX19fX19fCg==
    server: https://masterclass-cluster-dns-7890.hcp.westeurope.azmk8s.io:443
  name: masterclass-cluster
contexts:
- context:
    cluster: masterclass-cluster
    user: clusterUser_Cumulus_Masterclass
  name: masterclass-cluster
current-context: masterclass-cluster
kind: Config
preferences: {}
users:
- name: clusterUser_Cumulus_Masterclass
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURSekNDQWZlZ0F3SUJBZ0lRRm9LcmxXWThPclU0Zk01dzY1L1pIekFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVJRd0dnWURWUVFERXd3cmRXSmxjbTVsZEdWeXp6R0NfX19fX19fX0VORE9GR19fX19fX19fCg==
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFLQ0FRRUF6clU0Zk01dzY1L1pIekFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVJRd0dnWURWUVFERXd3cmRXSmxjbTVsZEdWeXp6R0NfX19fX19fX0VORE9GR19fX19fX19fCg==
